[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions-internal"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  functions = ".netlify/functions-internal"
  environment = { NODE_ENV = "development" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200